server:
  port: 9001

spring:
  application:
    name: feishubot
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    password: ${SPRING_REDIS_PASSWORD}
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0

my-config:
  app-id: 
  app-secret: 
  encrypt-key: 
  verification-token: 
  proxy-url: http://rnproxy.zhangjiashu.tech
  user-name: admin
  password: admin

logging:
  level:
    root: info
    com.zjs.feishubot: debug
    com.lark.oapi.event.EventDispatcher: OFF
